Use FIAP_1_GestorContatos;

GO

INSERT INTO Regiao (DDD, Nome) VALUES 
('11', 'São Paulo - Capital'),
('12', 'São Paulo - Vale do Paraíba e Litoral Norte'),
('13', 'São Paulo - Baixada Santista'),
('14', 'São Paulo - Bauru e Região'),
('15', 'São Paulo - Sorocaba e Região'),
('16', 'São Paulo - Ribeirão Preto e Região'),
('17', 'São Paulo - São José do Rio Preto e Região'),
('18', 'São Paulo - Presidente Prudente e Região'),
('19', 'São Paulo - Campinas e Região'),
('21', 'Rio de Janeiro - Capital e Região Metropolitana'),
('22', 'Rio de Janeiro - Norte e Região dos Lagos'),
('24', 'Rio de Janeiro - Centro-Sul Fluminense'),
('27', 'Espírito Santo - Norte'),
('28', 'Espírito Santo - Sul'),
('31', 'Minas Gerais - Belo Horizonte e Região Metropolitana'),
('32', 'Minas Gerais - Zona da Mata'),
('33', 'Minas Gerais - Leste e Vale do Rio Doce'),
('34', 'Minas Gerais - Triângulo Mineiro e Alto Paranaíba'),
('35', 'Minas Gerais - Sul e Sudoeste'),
('37', 'Minas Gerais - Centro-Oeste'),
('38', 'Minas Gerais - Norte de Minas'),
('41', 'Paraná - Curitiba e Região Metropolitana'),
('42', 'Paraná - Centro-Sul e Campos Gerais'),
('43', 'Paraná - Norte e Norte Pioneiro'),
('44', 'Paraná - Noroeste'),
('45', 'Paraná - Oeste'),
('46', 'Paraná - Sudoeste'),
('47', 'Santa Catarina - Norte'),
('48', 'Santa Catarina - Grande Florianópolis e Sul'),
('49', 'Santa Catarina - Oeste'),
('51', 'Rio Grande do Sul - Porto Alegre e Região Metropolitana'),
('53', 'Rio Grande do Sul - Pelotas e Litoral Sul'),
('54', 'Rio Grande do Sul - Serra Gaúcha'),
('55', 'Rio Grande do Sul - Noroeste'),
('61', 'Distrito Federal e Entorno'),
('62', 'Goiás - Goiânia e Região Metropolitana'),
('63', 'Tocantins'),
('64', 'Goiás - Sudeste'),
('65', 'Mato Grosso - Cuiabá e Região Metropolitana'),
('66', 'Mato Grosso - Norte e Noroeste'),
('67', 'Mato Grosso do Sul'),
('68', 'Acre'),
('69', 'Rondônia'),
('71', 'Bahia - Salvador e Região Metropolitana'),
('73', 'Bahia - Sul'),
('74', 'Bahia - Norte'),
('75', 'Bahia - Nordeste'),
('77', 'Bahia - Oeste'),
('79', 'Sergipe'),
('81', 'Pernambuco - Região Metropolitana do Recife'),
('82', 'Alagoas'),
('83', 'Paraíba'),
('84', 'Rio Grande do Norte'),
('85', 'Ceará - Fortaleza e Região Metropolitana'),
('86', 'Piauí - Norte e Teresina'),
('87', 'Pernambuco - Interior'),
('88', 'Ceará - Interior'),
('89', 'Piauí - Sul'),
('91', 'Pará - Belém e Região Metropolitana'),
('92', 'Amazonas - Manaus e Região Metropolitana'),
('93', 'Pará - Oeste'),
('94', 'Pará - Sudeste'),
('95', 'Roraima'),
('96', 'Amapá'),
('97', 'Amazonas - Interior'),
('98', 'Maranhão - São Luís e Região Metropolitana'),
('99', 'Maranhão - Interior');
